export const KEY = 'kikki-closet:v1';
export const CATEGORIES = ['상의','하의','속옷','신발','겉옷','소품'];
export const PROFILE_FIELDS = ['나이대','직업','생활수준','생활환경','배경·복식 문화','브랜드 성향','선택 성향','패션 관심도','스타일','색상','핏·소재','신발·소품','관리 습관','고정 조건'];
export const DEFAULTS = {enabled:false,profileId:'',worlds:[],target:'both',fixed:false,wardrobeSize:16,newItems:'보통',variety:'보통',detail:2,brands:true,mascot:true,auto:true};
export const clone = x => structuredClone(x);
export function branchId(){if(globalThis.crypto?.randomUUID)return crypto.randomUUID();const bytes=new Uint32Array(4);globalThis.crypto.getRandomValues(bytes);return 'branch-'+[...bytes].map(x=>x.toString(16).padStart(8,'0')).join('');}
export const text = (x,n=400) => typeof x==='string'?x.replace(/<\/?kikki_outfit\b[^>]*>/gi,'').trim().slice(0,n):'';
export function emptyState(){return {scene:{time:'불명',place:'불명',activity:'불명',weather:'불명'},people:{character:{nude:false,items:[]},persona:{nude:false,items:[]}}};}
export function hash(value){let h=2166136261;for(const c of String(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return (h>>>0).toString(36);}
export function visibleMessages(chat){return chat.filter(m=>!m.is_system&&!m.is_hidden&&!m.extra?.is_hidden).map((m,i)=>({id:String(m.extra?.kikki_id||m.send_date||i),swipe:m.swipe_id??0,role:m.is_user?'user':'character',name:text(m.name,80),content:text(String(m.mes||'').replace(/<kikki_outfit\s*>[\s\S]*?<\/kikki_outfit\s*>/gi,''),12000)}));}
export function prefixKeys(messages){let key='root';return messages.map(m=>(key=hash(key+JSON.stringify(m))));}
export function outfitText(state, detail=2, brands=true){return ['character','persona'].flatMap((who)=>{const p=state?.people?.[who];if(!p||p.nude||!p.items.length)return [];return [(who==='character'?'캐릭터':'페르소나')+': '+p.items.map(i=>{const features=(i.features||[]).slice(0,detail).join(' ');return [i.color,features,i.name,brands&&i.brand?'('+i.brand+')':''].filter(Boolean).join(' ');}).join(', ')+'.'];}).join('\n');}
export function replaceTags(value,content,{keep=true}={}){let found=0;const replaced=String(value).replace(/<kikki_outfit\s*>[\s\S]*?<\/kikki_outfit\s*>/gi,()=>{found++;return found===1&&keep?`<kikki_outfit>\n${content}\n</kikki_outfit>`:'';});return {text:replaced,found,malformed:(!found&&/<\/?kikki_outfit\b/i.test(value))};}
export function parseJSON(reply){if(typeof reply==='object'&&reply!==null&&!Array.isArray(reply))return reply;const str=String(reply).trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');const value=JSON.parse(str);if(!value||typeof value!=='object'||Array.isArray(value))throw Error('모델 응답이 JSON 객체가 아닙니다.');return value;}
function item(raw){if(!raw||!CATEGORIES.includes(raw.category)||!text(raw.name,100))throw Error('아이템의 카테고리나 이름이 잘못되었습니다.');return {id:text(raw.id,100)||'item-'+hash(JSON.stringify(raw)),category:raw.category,name:text(raw.name,100),color:text(raw.color,60),features:Array.isArray(raw.features)?raw.features.slice(0,6).map(x=>text(x,80)).filter(Boolean):[],brand:text(raw.brand,80),source:['추정 보유','기존 보유','구매','대여·지급'].includes(raw.source)?raw.source:'추정 보유',available:raw.available!==false};}
export function normalizeProfile(raw){const out={};for(const who of ['character','persona']){const p=raw[who];if(!p)continue;const fields={};for(const key of PROFILE_FIELDS){const f=p.fields?.[key];fields[key]={value:text(f?.value,500)||'불명',certainty:['명시','추정','불명'].includes(f?.certainty)?f.certainty:'불명',evidence:text(f?.evidence,500),locked:false};}out[who]={fields,wardrobe:(Array.isArray(p.wardrobe)?p.wardrobe:[]).slice(0,60).map(item)};const ids=new Set();for(const i of out[who].wardrobe){if(ids.has(i.id))throw Error('옷장 아이템 ID가 중복되었습니다.');ids.add(i.id);}}if(!Object.keys(out).length)throw Error('분석 대상의 프로필이 없습니다.');return out;}
export function validateState(raw,wardrobes){const state=emptyState();for(const k of Object.keys(state.scene))state.scene[k]=text(raw.scene?.[k],150)||'불명';const added={character:[],persona:[]};for(const who of ['character','persona']){const p=raw.people?.[who];if(!p||typeof p.nude!=='boolean'||!Array.isArray(p.items))throw Error('착장 판독에 인물 상태가 누락되었습니다.');const registry=new Map((wardrobes[who]||[]).map(i=>[i.id,i]));for(const r of (raw.newItems?.[who]||[])){const i=item(r);if(!registry.has(i.id)){added[who].push(i);registry.set(i.id,i);}}
const ids=new Set();for(const id of p.items){if(typeof id!=='string'||!registry.has(id)||!registry.get(id).available)throw Error('보유 옷에서 찾을 수 없는 아이템을 선택했습니다.');if(ids.has(id))continue;ids.add(id);state.people[who].items.push(clone(registry.get(id)));}if(p.nude&&ids.size)throw Error('완전 탈의와 착용 아이템이 동시에 지정되었습니다.');state.people[who].nude=p.nude;state.people[who].note=text(p.note,200);if(state.people[who].items.length>18)throw Error('착용 아이템이 너무 많습니다.');}return {state,added};}
export class Store {
 constructor(storage){this.storage=storage;this.epoch=0;this.data=this.load();}
 load(){const raw=this.storage.getItem(KEY);if(!raw)return {version:1,settings:clone(DEFAULTS),characters:{}};try{const d=JSON.parse(raw);if(d.version!==1||!d.characters||typeof d.characters!=='object')throw Error();d.settings={...DEFAULTS,...d.settings};return d;}catch{throw Error('저장 데이터가 손상되었습니다. 데이터 관리에서 초기화하세요.');}}
 save(){try{this.storage.setItem(KEY,JSON.stringify(this.data));}catch(error){this.invalidate();this.data=this.load();throw Error('저장 공간이 부족하거나 저장할 수 없습니다. 데이터 관리에서 정리하세요.',{cause:error});}}
 invalidate(){this.epoch++;}
 character(id){return this.data.characters[id];}
 createCharacter(id,name){this.data.characters[id]??={name,profiles:{},branches:{}};this.save();return this.character(id);}
 branch(id,bid){return this.character(id)?.branches[bid];}
 createBranch(id,name,copyFrom=null){const c=this.character(id);if(!c)throw Error('인물 분석을 먼저 시작하세요.');const bid=branchId();const copied=copyFrom?this.branch(id,copyFrom):null;c.branches[bid]={name:text(name,100)||'새 스토리',links:[],base:clone(copied?.current||emptyState()),current:clone(copied?.current||emptyState()),profiles:clone(copied?.profiles||c.profiles),extra:clone(copied?.extra||{character:[],persona:[]}),baseExtra:clone(copied?.extra||{character:[],persona:[]}),history:[],outfits:[],checkpoints:{},keys:[],suspended:false};this.save();return bid;}
 bind(id,bid,chatId){for(const b of Object.values(this.character(id).branches))b.links=b.links.filter(x=>x!==chatId);const b=this.branch(id,bid);b.links.push(chatId);b.suspended=false;this.invalidate();this.save();}
 find(id,chatId){return Object.entries(this.character(id)?.branches||{}).find(([,b])=>b.links.includes(chatId));}
 deleteChat(id,chatId){const entry=this.find(id,chatId);if(!entry)return;const [bid,b]=entry;b.links=b.links.filter(x=>x!==chatId);if(!b.links.length)delete this.character(id).branches[bid];this.invalidate();this.save();}
 deleteBranch(id,bid){delete this.character(id)?.branches[bid];this.invalidate();this.save();}
 deleteCharacter(id){delete this.data.characters[id];this.invalidate();this.save();}
 deleteAll(){this.invalidate();this.storage.removeItem(KEY);this.data={version:1,settings:clone(DEFAULTS),characters:{}};}
 resetChat(id,chatId){const [bid,b]=this.find(id,chatId)||[];if(!b)return;if(b.links.length>1){b.links=b.links.filter(x=>x!==chatId);const fresh=this.createBranch(id,'초기화된 채팅');this.bind(id,fresh,chatId);this.branch(id,fresh).suspended=true;}else{b.base=emptyState();b.current=emptyState();b.history=[];b.outfits=[];b.extra={character:[],persona:[]};b.baseExtra={character:[],persona:[]};b.checkpoints={};b.keys=[];b.suspended=true;}this.invalidate();this.save();}
}
export class Engine {
 constructor(store,request){this.store=store;this.request=request;this.controller=null;this.serial=0;}
 cancel(){this.serial++;this.controller?.abort();this.controller=null;}
 async read(id,bid,messages,{force=false,system,candidates=[]}={}){this.cancel();const serial=this.serial,epoch=this.store.epoch,b=this.store.branch(id,bid);if(!b||b.suspended)return null;const keys=prefixKeys(messages),key=keys.at(-1)||'root';if(!force&&key===b.keys.at(-1))return b.current;
let baseline=clone(b.base),extra=clone(b.baseExtra||{character:[],persona:[]}),history=[],outfits=[],start=0;for(let i=keys.length-1;i>=0;i--)if(b.checkpoints[keys[i]]){const cp=b.checkpoints[keys[i]];baseline=clone(cp.state);extra=clone(cp.extra);history=clone(cp.history);outfits=clone(cp.outfits);start=i+1;break;}
if(start===messages.length&&!force){b.current=baseline;b.extra=extra;b.history=history;b.outfits=outfits;b.keys=keys;this.store.save();return baseline;}
const wardrobes=Object.fromEntries(['character','persona'].map(w=>[w,[...(b.profiles[w]?.wardrobe||[]),...(extra[w]||[])]]));this.controller=new AbortController();const signal=this.controller.signal;
const raw=await this.request(system,{profiles:b.profiles,wardrobes,baseline,recent:history.slice(-5),recentOutfits:outfits.slice(-10),messages:messages.slice(start),candidates,options:this.store.data.settings},signal);
if(signal.aborted||serial!==this.serial||epoch!==this.store.epoch||this.store.branch(id,bid)!==b)return null;const {state,added}=validateState(raw,wardrobes);const changed=JSON.stringify(state)!==JSON.stringify(baseline);b.current=state;b.keys=keys;b.extra=extra;b.history=history;b.outfits=outfits;for(const w of ['character','persona'])b.extra[w].push(...added[w]);if(changed){b.history.push(clone(baseline));b.history=b.history.slice(-5);const outfit=outfitText(state);if(outfit&&b.outfits.at(-1)!==outfit)b.outfits.push(outfit);b.outfits=b.outfits.slice(-10);}delete b.checkpoints[key];b.checkpoints[key]={state:clone(state),extra:clone(b.extra),history:clone(b.history),outfits:clone(b.outfits)};const retained=Object.keys(b.checkpoints);for(const stale of retained.slice(0,-80))delete b.checkpoints[stale];this.store.save();this.controller=null;return state;}
}
