import {parseJSON,visibleMessages,hash,text,replaceTags} from './core.js';
export function createHost(context,service,worldInfo){
 const identity=()=>{const c=context(),ch=c.characters[c.characterId];if(!ch||c.groupId)return null;return {id:String(ch.avatar||c.characterId),name:ch.name||c.name2,chat:String(c.chatId||''),persona:String(c.powerUserSettings?.persona_description||''),personaKey:hash(String(c.powerUserSettings?.persona_description||'')+c.name1)};};
 return {context,identity,messages:(chat=context().chat)=>visibleMessages(chat),profiles:()=>service.getSupportedProfiles(),worlds:()=>worldInfo.world_names||[],
 async sources(settings){const c=context(),ch=c.characters[c.characterId];if(!ch)throw Error('캐릭터 채팅을 먼저 여세요.');const books=[];for(const name of settings.worlds){const book=await worldInfo.loadWorldInfo(name);books.push({name,entries:Object.values(book?.entries||{}).filter(e=>!e.disable).map(e=>({title:text(e.comment,150),content:text(e.content,12000)}))});}return {character:{name:ch.name,description:ch.description||ch.data?.description,personality:ch.personality||ch.data?.personality,scenario:ch.scenario||ch.data?.scenario},persona:{name:c.name1,description:c.powerUserSettings?.persona_description||''},books,target:settings.target,fixed:settings.fixed,wardrobeSize:settings.wardrobeSize};},
 async request(profileId,system,data,signal){if(signal?.aborted)throw Object.assign(Error('판독이 취소되었습니다.'),{name:'AbortError'});if(!profileId)throw Error('설정에서 연결 프로필을 선택하세요.');const profile=service.getProfile(profileId);service.validateProfile(profile);const ctl=new AbortController(),cancel=()=>ctl.abort();signal?.addEventListener('abort',cancel,{once:true});let timer;try{const work=service.sendRequest(profileId,[{role:'system',content:system},{role:'user',content:JSON.stringify(data)}],system.includes('인물 분석기')?6500:3500,{signal:ctl.signal,stream:false,extractData:true,includePreset:false,includeInstruct:true});const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>{ctl.abort();reject(Error('연결 모델 응답 시간이 초과되었습니다.'));},90000);ctl.signal.addEventListener('abort',()=>reject(Object.assign(Error('판독이 취소되었습니다.'),{name:'AbortError'})),{once:true});});const result=await Promise.race([work,timeout]);return parseJSON(result?.content??result);}finally{clearTimeout(timer);signal?.removeEventListener('abort',cancel);}},
 };
}
// Operate on the outgoing request only: never rewrite stored chat messages or templates.
export function injectPayload(payload,content,enabled=true){let found=0,malformed=false;const visit=(node)=>{if(typeof node==='string'){const r=replaceTags(node,content,{keep:enabled&&found===0});found+=r.found;malformed ||=r.malformed;return r.text;}if(Array.isArray(node))return node.map(visit);if(node&&typeof node==='object'){for(const key of ['prompt','messages','content','text'])if(Object.hasOwn(node,key))node[key]=visit(node[key]);}return node;};visit(payload);return {found,malformed};}
