import {CATEGORIES,PROFILE_FIELDS,clone,outfitText} from './core.js';

const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const loreKey=item=>JSON.stringify([item.book,String(item.uid)]);

export function createUI(api){
 const emptyDraft=()=>({target:'',sheet:{},available:{character:[],persona:[]},selected:{character:new Set(),persona:new Set()},status:{character:'',persona:''},busy:false});
 let dialog,sub,quick,bubble,notice,tab='actual',profileTab='character',lastFocus,sourceKey='';
 let draft=emptyDraft();
 const asset=name=>new URL('assets/'+name,api.base).href;
 const el=(tag,cls)=>{const node=document.createElement(tag);node.className=cls;return node;};
 const button=(label,action,cls='',attrs='')=>`<button type="button" class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
 const mascot=(cls='kc-inline-mascot')=>`<img class="${cls}" src="${asset('kikki-closed.webp')}" alt="">`;
 const title=label=>`<header><h3>${label}</h3>${button('×','sub-close','icon')}</header>`;
 const run=async fn=>{try{await fn();}catch(e){if(e.name!=='AbortError')error(e.message);}};

 async function copyText(value){
  if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(value);return;}catch{}}
  const input=document.createElement('textarea');input.value=value;input.style.cssText='position:absolute;opacity:0;width:1px;height:1px';(sub||dialog||document.body).append(input);input.select();const copied=document.execCommand('copy');input.remove();if(!copied)throw Error('자동 복사를 사용할 수 없습니다. 표시된 태그를 직접 복사하세요.');
 }
 function closeSub(){const old=sub;sub=null;old?.close();old?.remove();}
 function popup(label,body){closeSub();const d=el('dialog','kc-dialog kc-sub');sub=d;d.innerHTML=title(label)+`<div class="kc-content">${body}</div>`;document.body.append(d);d.addEventListener('click',click);d.addEventListener('change',change);d.addEventListener('close',()=>{d.remove();if(sub===d)sub=null;});d.showModal();return d;}
 function error(message){const d=sub?.open?sub:dialog?.open?dialog.querySelector('.kc-main'):null;if(d){let n=d.querySelector('.kc-error');if(!n){n=el('p','kc-error');n.setAttribute('role','alert');d.append(n);}n.textContent=message;n.scrollIntoView({block:'nearest'});}else globalThis.toastr?.error(message,'끼끼의상실');}
 function sceneLabel(state){if(!state)return '아직 착장을 판독하지 않았어요.';return [state.scene.place,state.scene.activity,state.scene.time,state.scene.weather].filter(x=>x&&x!=='불명').join(' · ')||'현재 상황 정보 없음';}
 function itemLabel(item,settings){return [item.color,...(item.features||[]).slice(0,settings.detail),item.name].filter(Boolean).join(' ');}
 function outfits(){const {branch,settings}=api.state();if(!branch)return '<p class="kc-muted">취향 분석으로 시작하거나 사용할 브랜치를 연결하세요.</p>';return ['character','persona'].map(who=>{const person=branch.current.people[who];return `<article class="kc-person"><div class="kc-label">${who==='character'?'캐릭터':'페르소나'}</div>${person.nude?'<p class="kc-muted">완전 탈의 · 주입 중단</p>':`<dl>${CATEGORIES.map(category=>{const items=person.items.filter(item=>item.category===category);return `<div class="kc-item"><dt>${category}</dt><dd>${items.length?items.map(item=>`${esc(itemLabel(item,settings))}${settings.brands&&item.brand?` <small>${esc(item.brand)}</small>`:''}`).join(' / '):'—'}</dd></div>`;}).join('')}</dl>`}</article>`;}).join('');}
 function select(name,label,values,value){return `<label class="kc-field">${label}<select name="${name}">${values.map(entry=>{const [id,text]=Array.isArray(entry)?entry:[entry,entry];return `<option value="${esc(id)}" ${String(value)===String(id)?'selected':''}>${esc(text)}</option>`;}).join('')}</select></label>`;}
 function checkbox(name,label,value){return `<label class="kc-check"><input type="checkbox" name="${esc(name)}" ${value?'checked':''}>${label}</label>`;}
 function ensureDraft(){const state=api.state(),identity=state.identity;const key=identity?`${identity.id}:${identity.chat}:${identity.personaKey}:${state.bid||''}`:'';if(key!==sourceKey){sourceKey=key;draft=emptyDraft();for(const who of ['character','persona'])draft.selected[who]=new Set(state.branch?.analysisSources?.selected?.[who]||[]);if(sub?.dataset.sourceTarget)closeSub();}}

 function renderMain(){
  if(!dialog?.open)return;
  const probe=el('span','');probe.style.color='var(--SmartThemeBodyColor,#393744)';dialog.append(probe);const rgb=getComputedStyle(probe).color.match(/[\d.]+/g)?.slice(0,3).map(Number)||[57,55,68];probe.remove();dialog.classList.toggle('kc-dark-paper',(rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722)>150);
  ensureDraft();
  const {branch,injectionError}=api.state();
  const main=dialog.querySelector('.kc-main');
  main.innerHTML=tab==='actual'?`<p class="kc-scene">${esc(sceneLabel(branch?.current))}</p>${branch?.suspended?'<p class="kc-muted">데이터를 초기화했어요. 판독 재개를 눌러 시작하세요.</p>':''}<div class="kc-outfits">${outfits()}</div><div class="kc-bottom">${button('착장 수정','edit')}${button('판독 재개','read')}${button('브랜치','branches')}</div>${injectionError?`<p class="kc-error">${esc(injectionError)}</p>`:''}`:options();
  dialog.querySelectorAll('[data-tab]').forEach(node=>{node.classList.toggle('active',node.dataset.tab===tab);node.setAttribute('aria-selected',node.dataset.tab===tab);});
 }
 function refresh(){const {settings}=api.state();renderMain();if(quick){quick.hidden=!settings.enabled||!settings.mascot;quick.querySelector('img').src=asset(bubble?.open?'kikki-open.webp':'kikki-closed.webp');placeQuick();}if(bubble?.open){bubble.querySelector('.kc-mini-content').innerHTML=`<p class="kc-scene">${esc(sceneLabel(api.state().branch?.current))}</p>${outfits()}`;placeBubble();}const enabled=document.querySelector('#kc-enabled');if(enabled)enabled.checked=settings.enabled;}

 function sourcePanel(who){
  const label=who==='character'?'캐릭터':'페르소나',sheet=draft.sheet[who],available=draft.available[who],selected=draft.selected[who];
  const groups=[...new Set(available.map(item=>item.book))].map(book=>{const entries=available.filter(item=>item.book===book);return `<details class="kc-lore-book"><summary>${esc(book)} · ${entries.filter(item=>selected.has(loreKey(item))).length}/${entries.length}</summary>${entries.map(item=>checkbox(`lore:${who}:${loreKey(item)}`,esc(item.title||`엔트리 ${item.uid}`),selected.has(loreKey(item)))).join('')}</details>`;}).join('');
  return `<section class="kc-source-panel"><div class="kc-source-card"><strong>${label} 시트</strong><p class="kc-muted">${sheet?`${esc(sheet.name)} · ${sheet.source.length}자 가져옴`:`${label} 시트를 아직 가져오지 않았습니다.`}</p><div class="kc-actions">${button(`${label} 시트 불러오기`,`sheet-load-${who}`)}${button('시트 보기',`sheet-view-${who}`,'',sheet?'':'disabled')}</div></div><div class="kc-source-card"><strong>${label} 연결 로어북</strong><p class="kc-muted">${draft.status[who]||'연결된 로어북을 불러온 뒤 필요한 엔트리만 체크하세요.'}</p><div class="kc-actions">${button(available.length?'연결 로어북 다시 읽기':'연결 로어북 불러오기',`lore-load-${who}`)}</div>${available.length?`<div class="kc-lore-list">${groups}<p class="kc-muted">${selected.size}개 엔트리 선택됨</p></div>`:''}</div></section>`;
 }
 function options(){
  const {settings,identity}=api.state();
  const targetLabel=draft.target==='character'?'캐릭터':draft.target==='persona'?'페르소나':'';
  const prepared=draft.target&&(draft.sheet[draft.target]?.source||draft.selected[draft.target].size);
  return `<div class="kc-analysis-head"><strong>${esc(identity?.name||'캐릭터 채팅을 여세요.')}</strong><span>대상을 고른 다음 그 대상의 자료만 불러옵니다.</span></div>${select('analysisTarget','분석 대상',[['','먼저 선택하세요'],['character','캐릭터'],['persona','페르소나']],draft.target)}${draft.target?`<div class="kc-source-summary"><strong>${targetLabel} 분석 자료</strong><span>${prepared?'자료 준비됨':'아직 가져오지 않음'}</span>${button('분석 자료 가져오기','open-sources','primary')}</div>`:'<p class="kc-muted">분석 대상을 선택해야 자료 가져오기 버튼이 열립니다.</p>'}<div class="kc-compact-options">${select('fixed','시트 평상복',[['false','스타일 예시'],['true','고정 착장']],String(settings.fixed))}${select('wardrobeSize','기본 옷장',[[10,'작게 · 10개'],[16,'보통 · 16개'],[24,'넉넉하게 · 24개']],settings.wardrobeSize)}${select('newItems','새 옷 추가',['적게','보통','많이'],settings.newItems)}${select('variety','조합 다양성',['적게','보통','많이'],settings.variety)}${select('detail','표시 디테일',[[1,'간단히'],[2,'보통'],[3,'자세히']],settings.detail)}${checkbox('brands','브랜드 표시',settings.brands)}</div><p class="kc-muted">채팅과 기억은 취향 분석에 보내지 않습니다.</p><div class="kc-actions kc-analysis-actions">${button('취향 보기','taste')}${button('브랜치 관리','branches')}</div>`;
 }

 function sourcePicker(){if(!draft.target)return error('분석 대상을 먼저 선택하세요.');const who=draft.target,label=who==='character'?'캐릭터':'페르소나';popup(`${label} 분석 자료 가져오기`,'');sub.dataset.sourceTarget=who;renderSourcePopup();}
 function renderSourcePopup(){if(!sub?.open||sub.dataset.sourceTarget!==draft.target)return;const who=draft.target,ready=draft.sheet[who]?.source||draft.available[who].some(item=>draft.selected[who].has(loreKey(item)));const opened=[...sub.querySelectorAll('.kc-lore-book')].map(node=>node.open);sub.querySelector('.kc-content').innerHTML=`${sourcePanel(who)}<p class="kc-muted">가져온 시트와 체크한 엔트리만 분석 모델에 보냅니다.</p><div class="kc-actions kc-analysis-actions">${button(draft.busy?'취향 분석 중…':'이 자료로 취향 분석','analyze','primary',ready&&!draft.busy?'':'disabled')}</div>`;sub.querySelectorAll('.kc-lore-book').forEach((node,index)=>node.open=opened[index]||false);}

 function open(){lastFocus=document.activeElement;if(!dialog){dialog=el('dialog','kc-dialog');dialog.id='kikki-closet-dialog';dialog.innerHTML=`<div class="kc-paper"></div><div class="kc-shell"><header><div class="kc-title">${mascot('kc-title-icon')}<div><small>WARDROBE DIARY</small><h2>끼끼의상실</h2></div></div></header><nav>${button('현재 착장','tab-actual','tag')}${button('선택지','tab-options','tag')}<div class="kc-nav-tools">${button('⚙','settings','icon')}${button('×','close','icon')}</div></nav><main class="kc-main"></main></div>`;dialog.querySelector('[data-action="tab-actual"]').dataset.tab='actual';dialog.querySelector('[data-action="tab-options"]').dataset.tab='options';dialog.addEventListener('click',click);dialog.addEventListener('change',change);dialog.addEventListener('close',()=>lastFocus?.focus());document.body.append(dialog);}bubble?.close();dialog.showModal();refresh();}
 function taste(){const branch=api.state().branch;if(!branch)return error('취향을 먼저 분석하세요.');const fields=PROFILE_FIELDS.map(key=>`<label class="kc-profile-field">${esc(key)}<input name="${esc(key)}"></label>`).join('');popup('취향 프로필',`<nav class="kc-profile-tabs">${button('캐릭터','profile-character','tag')}${button('페르소나','profile-persona','tag')}</nav><div class="kc-profile-grid"></div><div class="kc-actions">${button('수정 저장','save-profile','primary')}${button('기본 프로필에 반영','promote')}</div>`);sub.profileDraft=clone(branch.profiles);sub.fieldsMarkup=fields;renderProfile();}
 function renderProfile(){const profile=sub.profileDraft[profileTab];sub.querySelector('.kc-profile-grid').innerHTML=profile?sub.fieldsMarkup:'<p class="kc-muted">이 대상은 아직 분석하지 않았어요.</p>';if(profile)sub.querySelectorAll('input').forEach(input=>{const field=profile.fields[input.name];input.value=field?.value||'불명';const note=el('small','kc-muted');note.textContent=`${field?.certainty||'불명'}${field?.evidence?' · '+field.evidence:''}`;input.parentElement.append(note);input.addEventListener('input',()=>{profile.fields[input.name]={value:input.value,certainty:'명시',evidence:'사용자 수정',locked:true};});});sub.querySelectorAll('.kc-profile-tabs button').forEach(node=>node.classList.toggle('active',node.dataset.action==='profile-'+profileTab));}
 function settings(){const state=api.state();let profiles=[];try{profiles=api.profiles().map(p=>[p.id,(p.name||p.id)+' · '+(p.model||'')]);}catch{}popup('설정',`${checkbox('enabled','사용함',state.settings.enabled)}${select('profileId','SillyTavern 연결 프로필',[['','선택하세요'],...profiles],state.settings.profileId)}<div class="kc-actions">${button('프로필 새로고침','profiles-refresh')}${button('연결 확인','test')}</div><p class="kc-muted">모델·주소·키는 SillyTavern의 API 연결 메뉴에서 관리합니다.</p>${checkbox('auto','채팅 변화 자동 판독',state.settings.auto)}${checkbox('mascot','끼끼 빠른 확인 표시',state.settings.mascot)}<div class="kc-section">주입 위치</div><p class="kc-muted">모델에게 전달되는 인포블록에서 원하는 위치에 아래 두 줄을 한 번 붙여넣으세요.</p><pre>&lt;kikki_outfit&gt;\n&lt;/kikki_outfit&gt;</pre>${button('태그 복사','copy')}<details><summary>주입 미리보기</summary><pre>${esc(outfitText(state.branch?.current,state.settings.detail,state.settings.brands)||'현재 착장 없음')}</pre></details><div class="kc-section">저장 데이터 관리</div><div class="kc-actions">${button('현재 채팅 데이터 삭제','delete-chat')}${button('캐릭터 전체 삭제','delete-character')}${button('전체 데이터 삭제','delete-all')}</div>`);}
 function branches(){const {character,bid}=api.state();popup('스토리 브랜치',`<div class="kc-actions">${button('기본으로 새 브랜치','new')}${button('현재 상태 복제','copy-branch')}</div>${character?Object.entries(character.branches).map(([id,b])=>`<div class="kc-branch"><span>${esc(b.name)}${id===bid?' · 현재':''}<small>연결 채팅 ${b.links.length}개</small></span><button data-action="use-branch" data-id="${esc(id)}">이어가기</button><button data-action="delete-branch" data-id="${esc(id)}">삭제</button></div>`).join(''):'<p class="kc-muted">취향 분석 후 브랜치를 만들 수 있어요.</p>'}`);}
 function edit(){const branch=api.state().branch;if(!branch)return error('브랜치를 먼저 연결하세요.');popup('현재 착장 수정',`${select('editWho','대상',[['character','캐릭터'],['persona','페르소나']],'character')}<div class="kc-edit-items"></div>${button('착장 저장','save-outfit','primary')}`);sub.peopleDraft=clone(branch.current.people);const fill=()=>{const who=sub.querySelector('[name="editWho"]').value,person=sub.peopleDraft[who],items=[...(branch.profiles[who]?.wardrobe||[]),...(branch.extra[who]||[])];sub.querySelector('.kc-edit-items').innerHTML=checkbox('nude','완전 탈의',person.nude)+items.map(item=>checkbox('item:'+item.id,esc(item.category+' · '+itemLabel(item,api.state().settings)),person.items.some(x=>x.id===item.id))).join('');sub.querySelectorAll('.kc-edit-items input').forEach(node=>node.addEventListener('change',()=>{if(node.name==='nude'){person.nude=node.checked;if(person.nude)person.items=[];fill();return;}person.nude=false;person.items=items.filter(item=>sub.querySelector(`[name="item:${CSS.escape(item.id)}"]`)?.checked);sub.querySelector('[name="nude"]').checked=false;}));};sub.querySelector('[name="editWho"]').addEventListener('change',fill);fill();}

 async function loadLore(who){const owner=draft;owner.status[who]='연결된 로어북을 읽는 중…';renderSourcePopup();const entries=await api.lore(who);ensureDraft();if(owner!==draft)return;draft.available[who]=entries;draft.selected[who]=new Set([...draft.selected[who]].filter(key=>entries.some(item=>loreKey(item)===key)));draft.status[who]=entries.length?`연결 로어북 ${new Set(entries.map(item=>item.book)).size}개 · 필요한 엔트리를 체크하세요.`:'연결된 로어북이 없습니다.';renderSourcePopup();}
 function buildSelection(){const who=draft.target;return {targets:[who],sources:{[who]:{sheet:draft.sheet[who]||null,lore:draft.available[who].filter(item=>draft.selected[who].has(loreKey(item))).map(item=>({book:item.book,uid:item.uid,title:item.title,content:item.content}))}}};}
async function click(event){const node=event.target.closest('button');if(!node||!node.dataset.action||node.disabled)return;await run(async()=>{const action=node.dataset.action;if(action==='close')dialog.close();else if(action==='sub-close')closeSub();else if(action==='tab-actual'){tab='actual';refresh();}else if(action==='tab-options'){tab='options';refresh();}else if(action==='settings')settings();else if(action==='taste')taste();else if(action==='open-sources')sourcePicker();else if(action.startsWith('sheet-load-')){const who=action.slice(11);const owner=draft;const sheet=await api.sheet(who);ensureDraft();if(owner!==draft)return;draft.sheet[who]=sheet;renderSourcePopup();}else if(action.startsWith('sheet-view-')){const who=action.slice(11),sheet=draft.sheet[who];if(sheet){let preview=sub.querySelector('.kc-source-preview');if(preview){preview.remove();}else{preview=el('pre','kc-source-preview');preview.textContent=sheet.source;node.closest('.kc-source-card').append(preview);}}}else if(action.startsWith('lore-load-'))await loadLore(action.slice(10));else if(action==='analyze'){if(draft.busy)return;const owner=draft,who=draft.target;owner.busy=true;renderSourcePopup();try{const saved=await api.analyze(buildSelection());if(saved){profileTab=who;closeSub();taste();}}finally{owner.busy=false;renderSourcePopup();}}else if(action==='read'){const state=api.state();if(state.branch)state.branch.suspended=false;await api.read();}else if(action==='profile-character'||action==='profile-persona'){profileTab=action.slice(8);renderProfile();}else if(action==='save-profile'){api.saveProfiles(sub.profileDraft);closeSub();}else if(action==='promote'){if(confirm('이 취향을 기본 프로필에 반영할까요?')){api.saveProfiles(sub.profileDraft);api.promote();closeSub();}}else if(action==='branches')branches();else if(action==='new'||action==='copy-branch'){const name=prompt('브랜치 이름','새 스토리');if(name!==null){await api.newBranch(action==='new'?'new':'copy',name);closeSub();}}else if(action==='use-branch'){await api.newBranch('existing','',node.dataset.id);closeSub();}else if(action==='delete-branch'){if(confirm('이 브랜치와 연결된 착장 기록을 삭제할까요?')){api.remove('branch',node.dataset.id);branches();}}else if(action==='edit')edit();else if(action==='save-outfit'){api.saveOutfit(sub.peopleDraft);closeSub();}else if(action==='profiles-refresh'){settings();}else if(action==='test'){await api.testConnection();node.textContent='연결 확인됨';}else if(action==='copy'){await copyText('<kikki_outfit>\n</kikki_outfit>');node.textContent='복사됨';}else if(['delete-chat','delete-character','delete-all'].includes(action)){const kind=action.slice(7);if(confirm(kind==='chat'?'현재 채팅의 착장 데이터를 초기화할까요? 공유 브랜치는 다른 채팅을 보존합니다.':kind==='character'?'이 캐릭터의 모든 프로필·옷장·브랜치를 삭제할까요?':'끼끼의상실의 설정과 저장 데이터 전부를 삭제할까요?')){api.remove(kind);closeSub();}}});}
 function change(event){const name=event.target.name;if(!name||name==='editWho'||name.startsWith('item:')||name==='nude')return;if(name==='analysisTarget'){draft.target=event.target.value;refresh();return;}if(name.startsWith('lore:')){const [,who,...rest]=name.split(':');const key=rest.join(':');event.target.checked?draft.selected[who].add(key):draft.selected[who].delete(key);renderSourcePopup();return;}let value=event.target.type==='checkbox'?event.target.checked:event.target.value;if(['detail','wardrobeSize'].includes(name))value=Number(value);if(name==='fixed')value=value==='true';api.updateSettings({[name]:value});}

 function mini(){if(bubble?.open){bubble.close();refresh();return;}bubble??=el('dialog','kc-bubble');bubble.innerHTML=`<header><span>지금 입고 있는 옷</span>${button('×','mini-close','icon')}</header><div class="kc-mini-content"></div>${button('의상실 펼치기 ↗','mini-open')}`;if(!bubble.isConnected){document.body.append(bubble);bubble.addEventListener('click',event=>{const action=event.target.closest('button')?.dataset.action;if(action==='mini-close')bubble.close();if(action==='mini-open'){bubble.close();open();}refresh();});bubble.addEventListener('close',refresh);}bubble.showModal();refresh();}
 function placeQuick(){const position=api.state().settings.mascotPosition;if(!quick||quick.hidden)return;if(!position||!Number.isFinite(position.x)||!Number.isFinite(position.y)){quick.style.left='';quick.style.top='';quick.style.right='';quick.style.bottom='';return;}quick.style.right='auto';quick.style.bottom='auto';quick.style.left=Math.max(0,Math.min(1,position.x))*(innerWidth-quick.offsetWidth)+'px';quick.style.top=Math.max(0,Math.min(1,position.y))*(innerHeight-quick.offsetHeight)+'px';}
 function placeBubble(){if(!bubble?.open)return;const rect=quick.getBoundingClientRect(),width=bubble.offsetWidth,height=bubble.offsetHeight,leftSide=rect.left>innerWidth/2,x=Math.max(8,Math.min(innerWidth-width-8,leftSide?rect.left-width-8:rect.right+8)),y=Math.max(8,Math.min(innerHeight-height-8,rect.top+rect.height/2-height/2));bubble.style.inset='auto';bubble.style.left=x+'px';bubble.style.top=y+'px';bubble.style.setProperty('--kc-tail-x',(leftSide?x+width:x-9)+'px');bubble.style.setProperty('--kc-tail-y',Math.max(y+10,Math.min(y+height-10,rect.top+rect.height/2))+'px');bubble.style.setProperty('--kc-tail-direction',leftSide?'1':'-1');}
 function draggable(){let drag,suppress=false;quick.querySelector('img').draggable=false;quick.style.touchAction='none';quick.addEventListener('pointerdown',event=>{if(event.button!==0||!event.isPrimary)return;const rect=quick.getBoundingClientRect();drag={id:event.pointerId,x:event.clientX,y:event.clientY,left:rect.left,top:rect.top,moved:false};if(event.isTrusted)quick.setPointerCapture(event.pointerId);});quick.addEventListener('pointermove',event=>{if(!drag||drag.id!==event.pointerId)return;const dx=event.clientX-drag.x,dy=event.clientY-drag.y;if(!drag.moved&&Math.hypot(dx,dy)<6)return;drag.moved=true;event.preventDefault();quick.style.right='auto';quick.style.bottom='auto';quick.style.left=Math.max(0,Math.min(innerWidth-quick.offsetWidth,drag.left+dx))+'px';quick.style.top=Math.max(0,Math.min(innerHeight-quick.offsetHeight,drag.top+dy))+'px';});const finish=event=>{if(!drag||drag.id!==event.pointerId)return;const moved=drag.moved;drag=null;if(moved){suppress=true;const rect=quick.getBoundingClientRect();api.updateSettings({mascotPosition:{x:rect.left/Math.max(1,innerWidth-rect.width),y:rect.top/Math.max(1,innerHeight-rect.height)}});setTimeout(()=>suppress=false,0);}};quick.addEventListener('pointerup',finish);quick.addEventListener('pointercancel',finish);quick.addEventListener('lostpointercapture',finish);quick.addEventListener('click',event=>{if(suppress){event.preventDefault();event.stopImmediatePropagation();}},true);window.addEventListener('resize',()=>{placeQuick();placeBubble();});}
 function toast(show){if(!notice){notice=el('div','kc-toast');notice.textContent='의상을 맞춰보고 있습니다';notice.setAttribute('role','status');}if(show){const parent=sub?.open?sub:dialog?.open?dialog:document.body;if(notice.parentElement!==parent)parent.append(notice);}else notice.remove();}
 function mount(){const settingsPanel=document.querySelector('#extensions_settings2')||document.querySelector('#extensions_settings');if(settingsPanel){const block=el('details','kc-extension-settings');block.innerHTML=`<summary>${mascot('kc-settings-icon')}<span>끼끼의상실</span></summary><label class="kc-check"><input id="kc-enabled" type="checkbox">사용함</label><button type="button">의상실 열기</button>`;block.querySelector('input').addEventListener('change',event=>api.updateSettings({enabled:event.target.checked}));block.querySelector('button').addEventListener('click',open);settingsPanel.append(block);}const menu=document.querySelector('#extensionsMenu');if(menu){const menuButton=el('button','list-group-item flex-container flexGap5 kc-menu-button');menuButton.type='button';menuButton.innerHTML=`${mascot('kc-menu-icon')}<span>끼끼의상실</span>`;menuButton.addEventListener('click',open);menu.append(menuButton);}quick=el('button','kc-mascot');quick.type='button';quick.setAttribute('aria-label','끼끼 현재 착장');quick.innerHTML=`<img src="${asset('kikki-closed.webp')}" alt="끼끼">`;quick.addEventListener('click',mini);document.body.append(quick);draggable();refresh();}
 return {mount,refresh,toast,error,open};
}
