import {CATEGORIES,PROFILE_FIELDS,clone,outfitText,text} from './core.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createUI(api){
 let dialog,sub,quick,bubble,notice,tab='actual',profileTab='character',lastFocus;
 const asset=name=>new URL('assets/'+name,api.base).href;
 const el=(tag,cls)=>{const e=document.createElement(tag);e.className=cls;return e;};
 const run=async(fn)=>{try{await fn();}catch(e){if(e.name!=='AbortError')error(e.message);}};
 async function copyText(value){if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(value);return;}catch{}}const input=document.createElement('textarea');input.value=value;input.style.cssText='position:absolute;opacity:0;width:1px;height:1px';(sub||dialog||document.body).append(input);input.select();const copied=document.execCommand('copy');input.remove();if(!copied)throw Error('자동 복사를 사용할 수 없습니다. 표시된 태그를 직접 복사하세요.');}
 const button=(label,action,cls='')=>`<button type="button" class="${cls}" data-action="${action}">${label}</button>`;
 const title=(label)=>`<header><h3>${label}</h3>${button('×','sub-close','icon')}</header>`;
 function closeSub(){const old=sub;sub=null;old?.close();old?.remove();}
 function popup(label,body){closeSub();const d=el('dialog','kc-dialog kc-sub');sub=d;d.innerHTML=title(label)+`<div class="kc-content">${body}</div>`;document.body.append(d);d.addEventListener('click',click);d.addEventListener('close',()=>{d.remove();if(sub===d)sub=null;});d.showModal();return d;}
 function error(msg){const d=dialog?.open?dialog:sub?.open?sub:null;if(d){let n=d.querySelector('.kc-error');if(!n){n=el('p','kc-error');n.setAttribute('role','alert');d.append(n);}n.textContent=msg;}else globalThis.toastr?.error(msg,'끼끼의상실');}
 function sceneLabel(state){if(!state)return '아직 착장을 판독하지 않았어요.';return [state.scene.place,state.scene.activity,state.scene.time,state.scene.weather].filter(x=>x&&x!=='불명').join(' · ')||'현재 상황 정보 없음';}
 function itemLabel(i,s){return [i.color,...(i.features||[]).slice(0,s.detail),i.name].filter(Boolean).join(' ');}
 function outfits(){const {branch:b,settings:s}=api.state();if(!b)return '<p class="kc-muted">취향 분석으로 시작하거나 사용할 브랜치를 연결하세요.</p>';return ['character','persona'].map(w=>{const p=b.current.people[w];return `<article class="kc-person"><div class="kc-label">${w==='character'?'캐릭터':'페르소나'}</div>${p.nude?'<p class="kc-muted">완전 탈의 · 주입 중단</p>':`<dl>${CATEGORIES.map(cat=>{const items=p.items.filter(i=>i.category===cat);return `<div class="kc-item"><dt>${cat}</dt><dd>${items.length?items.map(i=>`${esc(itemLabel(i,s))}${s.brands&&i.brand?` <small>${esc(i.brand)}</small>`:''}`).join(' / '):'—'}</dd></div>`;}).join('')}</dl>`}</article>`;}).join('');}
 function select(name,label,values,value){return `<label class="kc-field">${label}<select name="${name}">${values.map(v=>{const [id,l]=Array.isArray(v)?v:[v,v];return `<option value="${esc(id)}" ${String(value)===String(id)?'selected':''}>${esc(l)}</option>`;}).join('')}</select></label>`;}
 function checkbox(name,label,value){return `<label class="kc-check"><input type="checkbox" name="${name}" ${value?'checked':''}>${label}</label>`;}
 function refresh(){const {identity:i,branch:b,settings:s,injectionError}=api.state();if(dialog?.open){const main=dialog.querySelector('.kc-main');if(main){main.innerHTML=tab==='actual'?`<p class="kc-scene">${esc(sceneLabel(b?.current))}</p>${b?.suspended?'<p class="kc-muted">데이터를 초기화했어요. 판독 재개를 눌러 시작하세요.</p>':''}<div class="kc-outfits">${outfits()}</div><div class="kc-bottom">${button('착장 수정','edit')}${button('판독 재개','read')}${button('브랜치','branches')}</div>${injectionError?`<p class="kc-error">${esc(injectionError)}</p>`:''}`:options();}dialog.querySelectorAll('[data-tab]').forEach(e=>{e.classList.toggle('active',e.dataset.tab===tab);e.setAttribute('aria-selected',e.dataset.tab===tab);});}
 if(quick){quick.hidden=!s.enabled||!s.mascot;quick.querySelector('img').src=asset(bubble?.open?'kikki-open.webp':'kikki-closed.webp');placeQuick();}if(bubble?.open){bubble.querySelector('.kc-mini-content').innerHTML=`<p class="kc-scene">${esc(sceneLabel(b?.current))}</p>${outfits()}`;placeBubble();}const enabled=document.querySelector('#kc-enabled');if(enabled)enabled.checked=s.enabled;
 }
 function options(){const {settings:s,identity:i}=api.state();let worlds=[];try{worlds=api.worlds();}catch{}return `<div class="kc-section">${esc(i?.name||'캐릭터 채팅을 여세요.')}</div>${select('target','분석 대상',[['both','캐릭터 + 페르소나'],['character','캐릭터'],['persona','페르소나']],s.target)}${select('fixed','시트 평상복',[['false','스타일 예시'],['true','고정 착장']],String(s.fixed))}<details class="kc-books"><summary>읽을 로어북 선택 · ${s.worlds.length}개</summary>${worlds.length?worlds.map(n=>checkbox('world:'+n,esc(n),s.worlds.includes(n))).join(''):'<p class="kc-muted">등록된 로어북이 없습니다.</p>'}</details>${select('wardrobeSize','기본 옷장 규모',[[10,'작게 · 10개'],[16,'보통 · 16개'],[24,'넉넉하게 · 24개']],s.wardrobeSize)}${select('newItems','새 옷 추가 빈도',['적게','보통','많이'],s.newItems)}${select('variety','조합 다양성',['적게','보통','많이'],s.variety)}${select('detail','디테일 표시',[[1,'간단히'],[2,'보통'],[3,'자세히']],s.detail)}${checkbox('brands','브랜드 표시',s.brands)}<div class="kc-actions">${button('취향 분석','analyze','primary')}${button('취향 보기','taste')}${button('브랜치 관리','branches')}</div>`;}
 function open(){lastFocus=document.activeElement;if(!dialog){dialog=el('dialog','kc-dialog');dialog.id='kikki-closet-dialog';dialog.innerHTML=`<div class="kc-paper"></div><div class="kc-shell"><header><div><small>WARDROBE DIARY</small><h2>👕 끼끼의상실</h2></div><div>${button('⚙','settings','icon')}${button('×','close','icon')}</div></header><nav>${button('현재 착장','tab-actual','tag')}${button('선택지','tab-options','tag')}</nav><main class="kc-main"></main></div>`;dialog.querySelector('[data-action="tab-actual"]').dataset.tab='actual';dialog.querySelector('[data-action="tab-options"]').dataset.tab='options';dialog.addEventListener('click',click);dialog.addEventListener('change',change);dialog.addEventListener('close',()=>lastFocus?.focus());document.body.append(dialog);}bubble?.close();dialog.showModal();refresh();}
 function taste(){const {branch:b}=api.state();if(!b)return error('취향을 먼저 분석하세요.');const fields=PROFILE_FIELDS.map(k=>`<label class="kc-profile-field">${esc(k)}<input name="${esc(k)}"></label>`).join('');popup('취향 프로필',`<nav class="kc-profile-tabs">${button('캐릭터','profile-character','tag')}${button('페르소나','profile-persona','tag')}</nav><div class="kc-profile-grid"></div><div class="kc-actions">${button('수정 저장','save-profile','primary')}${button('기본 프로필에 반영','promote')}</div>`);sub.profileDraft=clone(b.profiles);sub.fieldsMarkup=fields;renderProfile();}
 function renderProfile(){const p=sub.profileDraft[profileTab];sub.querySelector('.kc-profile-grid').innerHTML=p?sub.fieldsMarkup:'<p class="kc-muted">이 대상은 아직 분석하지 않았어요.</p>';if(p)sub.querySelectorAll('input').forEach(input=>{const f=p.fields[input.name];input.value=f?.value||'불명';const note=el('small','kc-muted');note.textContent=`${f?.certainty||'불명'}${f?.evidence?' · '+f.evidence:''}`;input.parentElement.append(note);input.addEventListener('input',()=>{p.fields[input.name]={value:input.value,certainty:'명시',evidence:'사용자 수정',locked:true};});});sub.querySelectorAll('.kc-profile-tabs button').forEach(e=>e.classList.toggle('active',e.dataset.action==='profile-'+profileTab));}
 function settings(){const {settings:s}=api.state();let profiles=[];try{profiles=api.profiles().map(p=>[p.id,(p.name||p.id)+' · '+(p.model||'')]);}catch{}popup('설정',`${checkbox('enabled','사용함',s.enabled)}${select('profileId','연결 프로필',[['','선택하세요'],...profiles],s.profileId)}${button('연결 확인','test')}<p class="kc-muted">모델은 선택한 연결 프로필의 설정을 사용합니다.</p>${checkbox('auto','채팅 변화 자동 판독',s.auto)}${checkbox('mascot','끼끼 빠른 확인 표시',s.mascot)}<div class="kc-section">주입 위치</div><p class="kc-muted">모델에게 전달되는 인포블록에서 원하는 위치에 아래 두 줄을 한 번 붙여넣으세요.</p><pre>&lt;kikki_outfit&gt;\n&lt;/kikki_outfit&gt;</pre>${button('태그 복사','copy')}<details><summary>주입 미리보기</summary><pre>${esc(outfitText(api.state().branch?.current,s.detail,s.brands)||'현재 착장 없음')}</pre></details><div class="kc-section">저장 데이터 관리</div><div class="kc-actions">${button('현재 채팅 데이터 삭제','delete-chat')}${button('캐릭터 전체 삭제','delete-character')}${button('전체 데이터 삭제','delete-all')}</div>`);sub.addEventListener('change',change);}
 function branches(){const {character:c,bid}=api.state();popup('스토리 브랜치',`<div class="kc-actions">${button('기본으로 새 브랜치','new')}${button('현재 상태 복제','copy-branch')}</div>${c?Object.entries(c.branches).map(([id,b])=>`<div class="kc-branch"><span>${esc(b.name)}${id===bid?' · 현재':''}<small>연결 채팅 ${b.links.length}개</small></span><button data-action="use-branch" data-id="${esc(id)}">이어가기</button><button data-action="delete-branch" data-id="${esc(id)}">삭제</button></div>`).join(''):'<p class="kc-muted">취향 분석 후 브랜치를 만들 수 있어요.</p>'}`);}
 function edit(){const b=api.state().branch;if(!b)return error('브랜치를 먼저 연결하세요.');popup('현재 착장 수정',`${select('editWho','대상',[['character','캐릭터'],['persona','페르소나']],'character')}<div class="kc-edit-items"></div>${button('착장 저장','save-outfit','primary')}`);sub.peopleDraft=clone(b.current.people);const fill=()=>{const w=sub.querySelector('[name="editWho"]').value;const p=sub.peopleDraft[w],items=[...(b.profiles[w]?.wardrobe||[]),...(b.extra[w]||[])];sub.querySelector('.kc-edit-items').innerHTML=checkbox('nude','완전 탈의',p.nude)+items.map(i=>checkbox('item:'+i.id,esc(i.category+' · '+itemLabel(i,api.state().settings)),p.items.some(x=>x.id===i.id))).join('');sub.querySelectorAll('.kc-edit-items input').forEach(e=>e.addEventListener('change',()=>{if(e.name==='nude'){p.nude=e.checked;if(p.nude)p.items=[];fill();return;}p.nude=false;p.items=items.filter(i=>sub.querySelector(`[name="item:${CSS.escape(i.id)}"]`)?.checked);sub.querySelector('[name="nude"]').checked=false;}));};sub.querySelector('[name="editWho"]').addEventListener('change',fill);fill();}
 async function click(e){const b=e.target.closest('button');if(!b)return;await run(async()=>{switch(b.dataset.action){case 'close':dialog.close();break;case 'sub-close':closeSub();break;case 'tab-actual':tab='actual';refresh();break;case 'tab-options':tab='options';refresh();break;case 'settings':settings();break;case 'taste':taste();break;case 'analyze':await api.analyze();taste();break;case 'read':{const v=api.state();if(v.branch)v.branch.suspended=false;await api.read();break;}case 'profile-character':profileTab='character';renderProfile();break;case 'profile-persona':profileTab='persona';renderProfile();break;case 'save-profile':api.saveProfiles(sub.profileDraft);closeSub();break;case 'promote':if(confirm('이 취향을 기본 프로필에 반영할까요?')){api.saveProfiles(sub.profileDraft);api.promote();closeSub();}break;case 'branches':branches();break;case 'new':case 'copy-branch':{const name=prompt('브랜치 이름','새 스토리');if(name!==null){await api.newBranch(b.dataset.action==='new'?'new':'copy',name);closeSub();}break;}case 'use-branch':await api.newBranch('existing','',b.dataset.id);closeSub();break;case 'delete-branch':if(confirm('이 브랜치와 연결된 착장 기록을 삭제할까요?')){api.remove('branch',b.dataset.id);branches();}break;case 'edit':edit();break;case 'save-outfit':api.saveOutfit(sub.peopleDraft);closeSub();break;case 'test':await api.testConnection();b.textContent='연결 확인됨';break;case 'copy':await copyText('<kikki_outfit>\n</kikki_outfit>');b.textContent='복사됨';break;case 'delete-chat':case 'delete-character':case 'delete-all':{const kind=b.dataset.action.slice(7);if(confirm(kind==='chat'?'현재 채팅의 착장 데이터를 초기화할까요? 공유 브랜치는 다른 채팅을 보존합니다.':kind==='character'?'이 캐릭터의 모든 프로필·옷장·브랜치를 삭제할까요?':'끼끼의상실의 설정과 저장 데이터 전부를 삭제할까요?')){api.remove(kind);closeSub();}break;}}});}
 function change(e){const n=e.target.name;if(!n||n==='editWho'||n.startsWith('item:')||n==='nude')return;const s=api.state().settings;if(n.startsWith('world:')){const w=n.slice(6);api.updateSettings({worlds:e.target.checked?[...new Set([...s.worlds,w])]:s.worlds.filter(x=>x!==w)});return;}let v=e.target.type==='checkbox'?e.target.checked:e.target.value;if(['detail','wardrobeSize'].includes(n))v=Number(v);if(n==='fixed')v=v==='true';api.updateSettings({[n]:v});}
 function mini(){if(bubble?.open){bubble.close();refresh();return;}bubble??=el('dialog','kc-bubble');bubble.innerHTML=`<header><span>지금 입고 있는 옷</span>${button('×','mini-close','icon')}</header><div class="kc-mini-content"></div>${button('의상실 펼치기 ↗','mini-open')}`;if(!bubble.isConnected){document.body.append(bubble);bubble.addEventListener('click',e=>{const a=e.target.closest('button')?.dataset.action;if(a==='mini-close')bubble.close();if(a==='mini-open'){bubble.close();open();}refresh();});bubble.addEventListener('close',refresh);}bubble.showModal();refresh();}
 function placeQuick(){const p=api.state().settings.mascotPosition;if(!quick||quick.hidden)return;if(!p||!Number.isFinite(p.x)||!Number.isFinite(p.y)){quick.style.left='';quick.style.top='';quick.style.right='';quick.style.bottom='';return;}quick.style.right='auto';quick.style.bottom='auto';quick.style.left=Math.max(0,Math.min(1,p.x))*(innerWidth-quick.offsetWidth)+'px';quick.style.top=Math.max(0,Math.min(1,p.y))*(innerHeight-quick.offsetHeight)+'px';}
 function placeBubble(){if(!bubble?.open)return;const r=quick.getBoundingClientRect(),w=bubble.offsetWidth,h=bubble.offsetHeight;const leftSide=r.left>innerWidth/2;const x=Math.max(8,Math.min(innerWidth-w-8,leftSide?r.left-w-8:r.right+8));const y=Math.max(8,Math.min(innerHeight-h-8,r.top+r.height/2-h/2));bubble.style.inset='auto';bubble.style.left=x+'px';bubble.style.top=y+'px';bubble.style.setProperty('--kc-tail-x',(leftSide?x+w:x-9)+'px');bubble.style.setProperty('--kc-tail-y',Math.max(y+10,Math.min(y+h-10,r.top+r.height/2))+'px');bubble.style.setProperty('--kc-tail-direction',leftSide?'1':'-1');}
 function draggable(){let drag,suppress=false;quick.querySelector('img').draggable=false;quick.style.touchAction='none';quick.addEventListener('pointerdown',e=>{if(e.button!==0||!e.isPrimary)return;const r=quick.getBoundingClientRect();drag={id:e.pointerId,x:e.clientX,y:e.clientY,left:r.left,top:r.top,moved:false};if(e.isTrusted)quick.setPointerCapture(e.pointerId);});quick.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(!drag.moved&&Math.hypot(dx,dy)<6)return;drag.moved=true;e.preventDefault();quick.style.right='auto';quick.style.bottom='auto';quick.style.left=Math.max(0,Math.min(innerWidth-quick.offsetWidth,drag.left+dx))+'px';quick.style.top=Math.max(0,Math.min(innerHeight-quick.offsetHeight,drag.top+dy))+'px';});const finish=e=>{if(!drag||drag.id!==e.pointerId)return;const moved=drag.moved;drag=null;if(moved){suppress=true;const r=quick.getBoundingClientRect();api.updateSettings({mascotPosition:{x:r.left/Math.max(1,innerWidth-r.width),y:r.top/Math.max(1,innerHeight-r.height)}});setTimeout(()=>suppress=false,0);}};quick.addEventListener('pointerup',finish);quick.addEventListener('pointercancel',finish);quick.addEventListener('lostpointercapture',finish);quick.addEventListener('click',e=>{if(suppress){e.preventDefault();e.stopImmediatePropagation();}},true);window.addEventListener('resize',()=>{placeQuick();placeBubble();});}
 function toast(show){if(!notice){notice=el('div','kc-toast');notice.textContent='의상을 맞춰보고 있습니다';notice.setAttribute('role','status');}if(show){const parent=sub?.open?sub:dialog?.open?dialog:document.body;if(notice.parentElement!==parent)parent.append(notice);}else notice.remove();}
 function mount(){const settingsPanel=document.querySelector('#extensions_settings2')||document.querySelector('#extensions_settings');if(settingsPanel){const block=el('details','kc-extension-settings');block.innerHTML='<summary>👕 끼끼의상실</summary><label class="kc-check"><input id="kc-enabled" type="checkbox">사용함</label><button type="button">의상실 열기</button>';block.querySelector('input').addEventListener('change',e=>api.updateSettings({enabled:e.target.checked}));block.querySelector('button').addEventListener('click',open);settingsPanel.append(block);}const menu=document.querySelector('#extensionsMenu');if(menu){const b=el('button','list-group-item flex-container flexGap5');b.type='button';b.textContent='👕 끼끼의상실';b.addEventListener('click',open);menu.append(b);}quick=el('button','kc-mascot');quick.type='button';quick.setAttribute('aria-label','끼끼 현재 착장');quick.innerHTML=`<img src="${asset('kikki-closed.webp')}" alt="끼끼">`;quick.addEventListener('click',mini);document.body.append(quick);draggable();refresh();}
 return {mount,refresh,toast,error,open};
}
