import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.KIKKI_PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(fileURLToPath(new URL('..',import.meta.url)));
const fixture=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/scripts/extensions/third-party/CHAT_CLOSET/style.css"><style>:root{--SmartThemeBodyColor:#383240;--SmartThemeBlurTintColor:#f6f0e8;--SmartThemeQuoteColor:#886895;--SmartThemeBorderColor:#cfc2d8}body{margin:0;background:#eee7f0;font-family:Arial}#chat{position:fixed;inset:0;z-index:500;background:#ddd2e5;pointer-events:none}</style></head><body><div id="chat">실리 채팅 레이어</div><div id="extensions_settings"></div><div id="extensionsMenu"></div><script>
window.calls=[];window.listeners={};window.modelWait=null;const events=['GENERATE_AFTER_DATA','GENERATION_STARTED','MESSAGE_RECEIVED','MESSAGE_SWIPED','MESSAGE_EDITED','MESSAGE_UPDATED','MESSAGE_DELETED','MESSAGE_SWIPE_DELETED','GENERATION_ENDED','CHAT_CHANGED','GENERATION_STOPPED','CHAT_DELETED','CHAT_RENAMED'];window.TEST_CONTEXT={characters:[{avatar:'c.png',name:'서윤',chat:'chat-a',data:{name:'서윤',description:'학생. 단정한 캐주얼을 좋아함.',personality:'차분하고 실용적이다.',extensions:{world:'복식 규칙'}}}],characterId:0,chatId:'chat-a',getRequestHeaders:()=>({'Content-Type':'application/json'}),name1:'나',name2:'서윤',chat:[{send_date:'0',is_user:false,name:'서윤',mes:'집에서 쉬고 있다.'}],extensionSettings:{regex:[],disabledExtensions:[]},powerUserSettings:{persona_description:'실용적인 캐주얼 선호'},eventTypes:Object.fromEntries(events.map(x=>[x,x])),eventSource:{on(k,fn){(listeners[k]??=[]).push(fn)},async emit(k,...args){for(const fn of listeners[k]||[])await fn(...args)}}};
const shoe={id:'shoe',category:'footwear',name:'운동화',color:'흰색',features:['캔버스'],brand:'CONVERSE',source:'assumedOwned',available:true};const wardrobeKinds={top:['Oxford shirt','henley shirt','knit polo','linen shirt','rugby shirt','ribbed top','sweatshirt','turtleneck','vest','work shirt'],bottom:['straight trousers','wide-leg slacks','pleated trousers','jeans','chinos','shorts','corduroy trousers'],outerwear:['wool coat','denim jacket','rain jacket','blazer','puffer jacket'],footwear:['canvas sneakers','derby shoes','ankle boots','loafers','sandals']};
function fixtureWardrobe(targets,omit=false){const all=[];for(const [category,count] of Object.entries(targets)){for(let i=0;i<count-(omit&&category==='top'?1:0);i++)all.push(category==='footwear'&&i===0?shoe:{id:category+'-'+i,category,name:wardrobeKinds[category][i],color:i%2?'charcoal':'navy',features:['cotton','regular fit'],brand:i%2?'MUJI':'UNIQLO',source:'assumedOwned',available:true});}return all.concat({id:'socks',category:'underwear',name:'crew socks',color:'white',features:[],brand:'UNIQLO',available:true},{id:'belt',category:'accessory',name:'leather belt',color:'black',features:[],brand:'UNIQLO',available:true});}
window.SERVICE={getSupportedProfiles:()=>[{id:'profile',name:'테스트 연결',model:'fixture'}],getProfile:()=>({id:'profile'}),validateProfile:()=>{},async sendRequest(id,messages,tokens,options){window.calls.push({id,messages,tokens});if(window.modelWait)return await new Promise(resolve=>window.releaseModel=()=>resolve({content:JSON.stringify(window.nextScene)}));const system=messages[0].content,data=JSON.parse(messages[1].content);if(system.startsWith('You complete an existing wardrobe'))return {content:JSON.stringify({wardrobe:window.failWardrobeFill?[]:fixtureWardrobe(data.wardrobeTargets).filter(i=>Object.hasOwn(data.missingByCategory,i.category)&&!data.existingWardrobe.some(e=>e.id===i.id)),wardrobeExceptions:{}})};if(system.includes('wardrobe-profile analyst'))return {content:JSON.stringify({character:{fields:{occupation:{value:'Student',certainty:'explicit',evidence:'Character sheet'},style:{value:'Quiet tailoring with subtle variations in texture and proportion. '.repeat(16)+'END OF REPORT',certainty:'inferred',evidence:'Prefers practical clothing and restrained colors.'}},wardrobe:fixtureWardrobe(data.wardrobeTargets,true)}})};if(system.includes('wardrobe report translator'))return {content:JSON.stringify({texts:data.texts.map(text=>text?'자연스럽고 차분한 스타일. '+text:'')})};if(system.startsWith('Return only'))return {content:'{"ok":true}'};const last=data.messages.at(-1)?.content||data.contextMessages?.at(-1)?.content||'';return {content:JSON.stringify({scene:{place:last.includes('로비')?'Lobby':last.includes('집')?'집':'거리',activity:'이동'},people:{character:{nude:/모두 벗|옷을 벗/.test(last),items:/모두 벗|옷을 벗/.test(last)?[]:last.includes('로비')?data.outfitMemory.character.beforeUndress:last.includes('맨발')?[]:['shoe']},persona:{nude:false,items:[]}},newItems:{character:[],persona:[]}})};}};
</script><script type="module" src="/scripts/extensions/third-party/CHAT_CLOSET/index.js"></script></body></html>`;
let serverFile=null;let uploadCount=0;
const server=createServer(async(req,res)=>{try{const u=req.url.split('?')[0];if(u==='/user/files/kikki-closet-state.json'){res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.statusCode=serverFile?200:404;res.end(serverFile||'');return;}if(u==='/api/files/upload'){let body='';for await(const chunk of req)body+=chunk;const data=JSON.parse(body);assert.equal(data.name,'kikki-closet-state.json');serverFile=Buffer.from(data.data,'base64').toString('utf8');uploadCount++;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({path:'user/files/kikki-closet-state.json'}));return;}if(u==='/'){res.setHeader('Content-Type','text/html');res.end(fixture);return;}const modules={'/scripts/extensions.js':'export function getContext(){return window.TEST_CONTEXT}', '/scripts/extensions/shared.js':'export const ConnectionManagerRequestService=window.SERVICE;', '/scripts/personas.js':'export const user_avatar="";', '/scripts/world-info.js':'export const world_info={charLore:[]};export async function loadWorldInfo(){return {entries:{1:{comment:"날씨",content:"겨울에는 겉옷",disable:false},2:{comment:"비활성",content:"제외",disable:true}}}}'};if(modules[u]){res.setHeader('Content-Type','text/javascript');res.end(modules[u]);return;}const rel=u.replace('/scripts/extensions/third-party/CHAT_CLOSET/','');const file=path.resolve(root,rel);if(!file.startsWith(root+path.sep))throw Error('path');const bytes=await readFile(file);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.webp')?'image/webp':'text/plain');res.end(bytes);}catch{res.statusCode=404;res.end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
let browser;try{
browser=await chromium.launch({channel:process.env.KIKKI_BROWSER_CHANNEL||(process.platform==='win32'?'msedge':undefined),headless:true});const page=await browser.newPage({viewport:{width:360,height:780}});const saved=()=>page.waitForFunction(()=>document.querySelector('.kc-storage-status')?.textContent==='서버 저장됨');const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:'+server.address().port);assert.equal(await page.locator('#extensionsMenu .kc-menu-icon').count(),1);await page.locator('.kc-extension-settings summary').click();await page.locator('#kc-enabled').check();await page.locator('.kc-mascot').waitFor({state:'visible',timeout:3000}).catch(async e=>{throw Error(JSON.stringify({errors,status:await page.locator('.kc-storage-status').allTextContents(),body:await page.locator('body').innerText()}));});const original=await page.locator('.kc-mascot').boundingBox();await page.mouse.move(original.x+20,original.y+20);await page.mouse.down();await page.mouse.move(60,180,{steps:12});await page.mouse.up();await saved();assert.equal(await page.locator('.kc-bubble[open]').count(),0);const moved=await page.locator('.kc-mascot').boundingBox();assert.ok(moved.x<80&&moved.y<200);await page.reload();await page.locator('.kc-extension-settings summary').click();const restored=await page.locator('.kc-mascot').boundingBox();assert.ok(Math.abs(restored.x-moved.x)<2&&Math.abs(restored.y-moved.y)<2);await page.locator('.kc-mascot').click();const bubbleBox=await page.locator('.kc-bubble').boundingBox();assert.ok(bubbleBox.x>=0&&bubbleBox.x+bubbleBox.width<=360);await page.locator('.kc-mascot').click();assert.equal(await page.locator('.kc-bubble[open]').count(),0);await page.evaluate(()=>{const q=document.querySelector('.kc-mascot'),r=q.getBoundingClientRect();q.dispatchEvent(new PointerEvent('pointerdown',{pointerId:22,pointerType:'touch',isPrimary:true,button:0,clientX:r.x+20,clientY:r.y+20,bubbles:true}));q.dispatchEvent(new PointerEvent('pointermove',{pointerId:22,pointerType:'touch',isPrimary:true,clientX:300,clientY:400,bubbles:true}));q.dispatchEvent(new PointerEvent('pointerup',{pointerId:22,pointerType:'touch',isPrimary:true,clientX:300,clientY:400,bubbles:true}));});assert.ok((await page.locator('.kc-mascot').boundingBox()).x>200);await saved();
// Lock stays saved, while tapping still opens and closes the mini panel.
await page.locator('.kc-extension-settings [name="mascotLocked"]').check();await saved();
const locked=await page.locator('.kc-mascot').boundingBox();
await page.evaluate(()=>{const q=document.querySelector('.kc-mascot'),r=q.getBoundingClientRect();for(const [type,x,y] of [['pointerdown',r.x+10,r.y+10],['pointermove',15,15],['pointerup',15,15]])q.dispatchEvent(new PointerEvent(type,{pointerId:9,pointerType:'touch',isPrimary:true,button:0,clientX:x,clientY:y,bubbles:true}));});
assert.deepEqual(await page.locator('.kc-mascot').boundingBox(),locked);
await page.locator('.kc-mascot').click();assert.equal(await page.locator('.kc-bubble[open]').count(),1);await page.locator('.kc-mascot').click();
await page.reload();await page.locator('.kc-extension-settings summary').click();assert.equal(await page.locator('.kc-extension-settings [name="mascotLocked"]').isChecked(),true);
await page.setViewportSize({width:780,height:360});await page.waitForTimeout(50);let q=await page.locator('.kc-mascot').boundingBox();assert.ok(q.x>=8&&q.y>=8&&q.x+q.width<=772&&q.y+q.height<=352);
await page.setViewportSize({width:360,height:780});await page.waitForTimeout(50);assert.deepEqual(await page.locator('.kc-mascot').boundingBox(),locked);
// Simulate mobile keyboard/pinch visual viewport offsets without altering the layout viewport.
await page.evaluate(()=>{for(const [key,value] of Object.entries({width:300,height:240,offsetLeft:30,offsetTop:120}))Object.defineProperty(visualViewport,key,{configurable:true,value});visualViewport.dispatchEvent(new Event('resize'));});
q=await page.locator('.kc-mascot').boundingBox();assert.ok(q.x>=38&&q.y>=128&&q.x+q.width<=322&&q.y+q.height<=352);
await page.locator('.kc-mascot').click();const smallBubble=await page.locator('.kc-bubble').boundingBox();assert.ok(smallBubble.x>=38&&smallBubble.y>=128&&smallBubble.x+smallBubble.width<=322&&smallBubble.y+smallBubble.height<=352);
assert.ok(smallBubble.x+smallBubble.width<=q.x||smallBubble.x>=q.x+q.width||smallBubble.y+smallBubble.height<=q.y||smallBubble.y>=q.y+q.height);await page.screenshot({path:path.join(root,'test-results/mascot-keyboard.png')});await page.locator('.kc-mascot').click();
await page.evaluate(()=>{for(const key of ['width','height','offsetLeft','offsetTop'])delete visualViewport[key];visualViewport.dispatchEvent(new Event('resize'));});
await page.locator('.kc-extension-settings .kc-reset').click();await saved();q=await page.locator('.kc-mascot').boundingBox();assert.ok(q.y>600&&q.x>280);
await page.locator('.kc-extension-settings .kc-open').click();assert.equal(await page.locator('.kc-paper').evaluate(e=>getComputedStyle(e).zIndex),'0');await page.locator('[data-action="settings"]').click();await page.locator('[name="profileId"]').selectOption('profile');await page.locator('[data-action="test"]').click();await page.locator('[name="chatTurns"]').fill('2');await page.locator('[name="chatTurns"]').dispatchEvent('change');await page.locator('[data-action="sub-close"]').click();await page.locator('[data-action="tab-options"]').click();assert.equal(await page.locator('[data-action="open-sources"]').count(),0);assert.equal(await page.locator('[name="wardrobeSize"]').count(),0);await page.locator('[name="wardrobeLevel:top"]').selectOption('low');await saved();await page.locator('[name="analysisTarget"]').selectOption('character');await page.locator('[data-action="open-sources"]').click();assert.match(await page.locator('.kc-sub h3').innerText(),/캐릭터/);assert.equal(await page.locator('[data-action="sheet-load-persona"]').count(),0);await page.locator('[data-action="sheet-load-character"]').click();await page.locator('[data-action="lore-load-character"]').click();assert.equal(await page.locator('.kc-lore-book input').count(),1);await page.locator('.kc-lore-book summary').click();await page.locator('.kc-lore-book input').check();await page.screenshot({path:path.join(root,'test-results/source-popup.png'),fullPage:true});await page.locator('[data-action="analyze"]').click();await page.locator('.kc-report').waitFor({state:'visible'});const analysisCall=await page.evaluate(()=>calls.find(call=>call.messages[0].content.includes('wardrobe-profile analyst')));const analysisData=JSON.parse(analysisCall.messages[1].content);assert.deepEqual(analysisData.targets,['character']);assert.equal(Object.hasOwn(analysisData.sources,'persona'),false);assert.equal(Object.hasOwn(analysisData,'messages'),false);assert.deepEqual(analysisData.wardrobeTargets,{top:4,bottom:5,outerwear:3,footwear:3});assert.equal(Object.hasOwn(analysisData,'wardrobeSize'),false);assert.equal(await page.evaluate(()=>calls.filter(c=>c.messages[0].content.startsWith('You complete an existing wardrobe')).length),1);assert.equal(await page.locator('.kc-report input').count(),0);assert.match(await page.locator('.kc-report').innerText(),/END OF REPORT/);
await page.screenshot({path:path.join(root,'test-results/report-mobile.png'),fullPage:true});
await page.setViewportSize({width:1000,height:900});await page.screenshot({path:path.join(root,'test-results/report-desktop.png'),fullPage:true});
assert.equal(await page.locator('.kc-report-value').evaluateAll(nodes=>nodes.every(n=>n.scrollWidth<=n.clientWidth+1&&n.scrollHeight<=n.clientHeight+1)),true);
await saved();const beforeTranslation=serverFile;
const mobileContext=await browser.newContext({viewport:{width:390,height:844}}),mobile=await mobileContext.newPage();mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto('http://127.0.0.1:'+server.address().port);await mobile.locator('.kc-extension-settings summary').click();assert.equal(await mobile.locator('#kc-enabled').isChecked(),true);assert.equal(await mobile.evaluate(()=>localStorage.getItem('kikki-closet:v1')),null);await mobile.locator('.kc-open').click();await mobile.locator('[data-action="tab-options"]').click();await mobile.locator('[data-action="taste"]').click();assert.match(await mobile.locator('.kc-report').innerText(),/Student|END OF REPORT/);await mobile.locator('[data-action="sub-close"]').click();

await page.locator('[data-action="translate-profile"]').click();await page.waitForFunction(()=>document.querySelector('[data-action="translate-profile"]')?.textContent==='원문 보기');
assert.match(await page.locator('.kc-report').innerText(),/자연스럽고 차분한/);assert.equal(serverFile,beforeTranslation);
await page.locator('[data-action="translate-profile"]').click();assert.match(await page.locator('.kc-report').innerText(),/END OF REPORT/);
await page.locator('[data-action="translate-profile"]').click();assert.equal(await page.evaluate(()=>calls.filter(c=>c.messages[0].content.includes('wardrobe report translator')).length),1);
await page.locator('[data-action="profile-persona"]').click();assert.equal(await page.locator('[data-action="translate-profile"]').isDisabled(),true);
await page.locator('[data-action="profile-character"]').click();await page.locator('[data-action="edit-profile"]').click();
assert.equal(await page.locator('[data-profile-field="직업"]').inputValue(),'Student');
await page.locator('[data-profile-field="직업"]').fill('Student and part-time tailor');
assert.equal(await page.locator('[data-profile-field="스타일"]').evaluate(n=>n.scrollHeight<=n.clientHeight+2),true);
await page.locator('[data-action="save-profile"]').click();await page.setViewportSize({width:360,height:780});await page.locator('[name="analysisTarget"]').selectOption('persona');await page.locator('[data-action="open-sources"]').click();assert.match(await page.locator('.kc-sub h3').innerText(),/페르소나/);assert.equal(await page.locator('[data-action="sheet-load-character"]').count(),0);assert.equal(await page.locator('[data-action="sheet-load-persona"]').count(),1);await page.locator('[data-action="sub-close"]').click();await page.locator('[data-action="tab-actual"]').click();
const center=await page.locator('#kikki-closet-dialog').boundingBox();assert.ok(Math.abs(center.x+center.width/2-180)<2);assert.ok(Math.abs(center.y+center.height/2-390)<2);assert.ok(Math.abs(center.width/center.height-2/3)<.002);await page.screenshot({path:path.join(root,'test-results/mobile.png'),fullPage:true});
const paperBox=await page.locator('.kc-paper').boundingBox();await page.locator('[data-action="tab-options"]').click();assert.deepEqual(await page.locator('.kc-paper').boundingBox(),paperBox);await page.locator('[data-action="tab-actual"]').click();assert.deepEqual(await page.locator('.kc-paper').boundingBox(),paperBox);const firstLabel=await page.locator('.kc-item dt').first().boundingBox();assert.ok(firstLabel.x>=paperBox.x+paperBox.width*.12);
async function readNow(){const count=await page.evaluate(()=>calls.length);await page.locator('[data-action="read"]').click();await page.waitForFunction(n=>calls.length>n,count);await page.locator('.kc-toast').waitFor({state:'detached'});await saved();}
await readNow();
const beforeRP=await page.evaluate(()=>calls.length);
await page.evaluate(async()=>{TEST_CONTEXT.chat.push({send_date:'1',is_user:true,mes:'외출 준비를 한다.'});await kikkiClosetInterceptor(TEST_CONTEXT.chat,4096,value=>window.aborted=value,'normal');const p={prompt:[{role:'system',content:'<kikki_outfit>OLD</kikki_outfit>'}]};await TEST_CONTEXT.eventSource.emit('GENERATE_AFTER_DATA',p,false);window.injected=p.prompt[0].content;});assert.equal(await page.evaluate(()=>window.aborted),undefined,await page.locator('.kc-error').allInnerTexts().then(x=>x.join(' / ')));assert.match(await page.evaluate(()=>window.injected),/운동화/);assert.doesNotMatch(await page.evaluate(()=>window.injected),/OLD|baseline|profiles/);await page.screenshot({path:path.join(root,'test-results/mobile-outfit.png'),fullPage:true});
assert.equal(await page.evaluate(()=>calls.length),beforeRP);assert.match(await page.evaluate(()=>window.injected),/NEVER add a clothing section/);
const readCount=await page.evaluate(()=>calls.length);await readNow();assert.ok(await page.evaluate(()=>calls.length)>readCount);
const preview=await page.evaluate(()=>JSON.parse(calls.at(-1).messages[1].content));assert.equal(preview.options.chatTurns,2);assert.equal(preview.messages.length,1);assert.ok(preview.contextMessages.length>0);
await readNow();assert.equal(await page.evaluate(()=>JSON.parse(calls.at(-1).messages[1].content).messages.length),0);
const mobileButtonSize=await page.locator('[data-action="edit"]').evaluate(n=>getComputedStyle(n).fontSize);
await page.setViewportSize({width:1000,height:900});assert.equal(await page.locator('.kc-item').first().evaluate(n=>getComputedStyle(n).fontSize),'13px');await page.screenshot({path:path.join(root,'test-results/desktop-outfit.png'),fullPage:true});
await page.setViewportSize({width:360,height:780});assert.equal(await page.locator('.kc-item').first().evaluate(n=>getComputedStyle(n).fontSize),'10px');assert.equal(await page.locator('[data-action="edit"]').evaluate(n=>getComputedStyle(n).fontSize),mobileButtonSize);
await page.evaluate(async()=>{TEST_CONTEXT.chat.push({send_date:'2',is_user:false,swipe_id:0,mes:'신발을 신고 밖으로 나갔다.'});await TEST_CONTEXT.eventSource.emit('MESSAGE_RECEIVED',2)});await page.waitForTimeout(500);await page.evaluate(async()=>{TEST_CONTEXT.chat[2].swipe_id=1;TEST_CONTEXT.chat[2].mes='맨발로 밖으로 나갔다.';await TEST_CONTEXT.eventSource.emit('MESSAGE_SWIPED',2)});await page.waitForTimeout(500);assert.equal(await page.locator('.kc-person').first().locator('dd').filter({hasText:'운동화'}).count(),0);
await page.evaluate(async()=>{TEST_CONTEXT.chat[2].is_system=true;await TEST_CONTEXT.eventSource.emit('MESSAGE_UPDATED',2)});await page.waitForTimeout(500);assert.ok(await page.locator('.kc-person').first().locator('dd').filter({hasText:'운동화'}).count());

// Streaming causes no reader request; duplicate completion events coalesce.
const beforeStreaming=await page.evaluate(()=>calls.length);
await page.evaluate(async()=>{await TEST_CONTEXT.eventSource.emit('GENERATION_STARTED','normal',{},false);TEST_CONTEXT.chat.push({send_date:'3',is_user:false,mes:'그는 코트를'});await TEST_CONTEXT.eventSource.emit('MESSAGE_UPDATED',3);});
await page.waitForTimeout(400);assert.equal(await page.evaluate(()=>calls.length),beforeStreaming);
await page.evaluate(async()=>{TEST_CONTEXT.chat[3].mes='그는 코트를 걸치고 집을 나섰다.';await TEST_CONTEXT.eventSource.emit('MESSAGE_RECEIVED',3);await TEST_CONTEXT.eventSource.emit('GENERATION_ENDED');await TEST_CONTEXT.eventSource.emit('MESSAGE_UPDATED',3);});
await page.waitForFunction(count=>calls.length===count+1,beforeStreaming);await page.waitForTimeout(400);assert.equal(await page.evaluate(()=>calls.length),beforeStreaming+1);
const beforeQuiet=await page.evaluate(()=>calls.length);
await page.evaluate(async()=>{TEST_CONTEXT.chat.push({send_date:'4',is_user:false,mes:'그는 미소 지으며 고개를 끄덕였다.'});await TEST_CONTEXT.eventSource.emit('MESSAGE_RECEIVED',4);await TEST_CONTEXT.eventSource.emit('GENERATION_ENDED');});
await page.waitForTimeout(450);assert.equal(await page.evaluate(()=>calls.length),beforeQuiet);
// Dismissing the toast does not cancel work or start another request.
await page.evaluate(()=>{window.modelWait=true;window.nextScene={scene:{place:'Home'},people:{character:{nude:false,items:['shoe']},persona:{nude:false,items:[]}},newItems:{}};});
await page.locator('[data-action="read"]').click();await page.locator('.kc-toast').waitFor({state:'visible'});const toastBox=await page.locator('.kc-toast').boundingBox();assert.ok(toastBox.y>600);await page.locator('.kc-toast').click();assert.equal(await page.locator('.kc-toast').count(),0);
const beforePendingRP=await page.evaluate(()=>calls.length);
await page.evaluate(()=>kikkiClosetInterceptor(TEST_CONTEXT.chat,4096,()=>{},'normal'));assert.equal(await page.evaluate(()=>calls.length),beforePendingRP);
await page.locator('[data-action="read"]').click();assert.equal(await page.evaluate(()=>calls.length),beforePendingRP);assert.equal(await page.locator('.kc-toast').count(),0);
await page.evaluate(()=>{window.modelWait=false;window.releaseModel();});await page.waitForTimeout(100);

// A failed completion must not persist partial wardrobes or overwrite an existing profile.
await page.locator('[data-action="tab-options"]').click();await page.locator('[name="wardrobeLevel:top"]').selectOption('high');await saved();
const beforeFailedAnalysis=serverFile;await page.evaluate(()=>window.failWardrobeFill=true);
await page.locator('[name="analysisTarget"]').selectOption('character');await page.locator('[data-action="open-sources"]').click();await page.locator('[data-action="sheet-load-character"]').click();await page.locator('[data-action="analyze"]').click();
await page.locator('.kc-sub .kc-error').waitFor();assert.match(await page.locator('.kc-sub .kc-error').innerText(),/완성하지 못/);assert.equal(serverFile,beforeFailedAnalysis);
await page.evaluate(()=>window.failWardrobeFill=false);await page.locator('[data-action="sub-close"]').click();await page.locator('[name="wardrobeLevel:top"]').selectOption('low');await saved();await page.locator('[data-action="tab-actual"]').click();

// Closet cards preserve selections across category/person tabs and scroll inside the centered popup.
await page.locator('[data-action="edit"]').click();assert.equal(await page.locator('.kc-wardrobe-tabs [role="tab"]').count(),6);
assert.equal(await page.locator('.kc-wardrobe-card').count(),4);assert.equal(await page.locator('.kc-wardrobe-detail').count(),0);
await page.locator('[name="item:top-0"]').check();await page.locator('[data-action="wardrobe-category"][data-category="bottom"]').click();assert.equal(await page.locator('.kc-wardrobe-card').count(),5);
await page.locator('[name="item:bottom-0"]').check();await page.locator('[data-action="wardrobe-person"][data-who="persona"]').click();assert.equal(await page.locator('.kc-wardrobe-card').count(),0);
await page.locator('[data-action="wardrobe-person"][data-who="character"]').click();assert.equal(await page.locator('[name="item:bottom-0"]').isChecked(),true);
await page.locator('[data-action="wardrobe-category"][data-category="top"]').click();assert.equal(await page.locator('[name="item:top-0"]').isChecked(),true);
let closetBox=await page.locator('.kc-wardrobe').boundingBox();assert.ok(Math.abs(closetBox.x+closetBox.width/2-180)<2);
assert.equal(await page.locator('.kc-wardrobe-shelf').evaluate(n=>getComputedStyle(n).gridTemplateColumns.split(' ').length),2);
assert.equal(await page.locator('.kc-wardrobe-pick').evaluateAll(nodes=>nodes.every(n=>n.scrollWidth<=n.clientWidth+1)),true);
await page.screenshot({path:path.join(root,'test-results/wardrobe-mobile.png')});
await page.setViewportSize({width:320,height:340});const compact=await page.locator('.kc-wardrobe').boundingBox();assert.ok(compact.y>=8&&compact.y+compact.height<=332);
assert.equal(await page.locator('.kc-wardrobe-shelf').evaluate(n=>n.scrollHeight>n.clientHeight),true);const footer=await page.locator('.kc-wardrobe-footer').boundingBox();assert.ok(footer.y+footer.height<=332);
await page.screenshot({path:path.join(root,'test-results/wardrobe-small.png')});await page.setViewportSize({width:360,height:780});
await page.setViewportSize({width:1000,height:900});assert.equal(await page.locator('.kc-wardrobe-shelf').evaluate(n=>getComputedStyle(n).gridTemplateColumns.split(' ').length),3);
await page.screenshot({path:path.join(root,'test-results/wardrobe-desktop.png')});await page.setViewportSize({width:360,height:780});
await page.locator('[data-action="save-outfit"]').click();await saved();
await page.evaluate(async()=>{TEST_CONTEXT.chat.push({send_date:'20',is_user:false,mes:'옷을 모두 벗었다.'});await TEST_CONTEXT.eventSource.emit('MESSAGE_RECEIVED',TEST_CONTEXT.chat.length-1);});
await page.waitForFunction(()=>document.querySelector('.kc-main')?.textContent.includes('완전 탈의'));await saved();
await page.evaluate(async()=>{TEST_CONTEXT.chat.push({send_date:'21',is_user:false,mes:'그들은 로비로 내려갔다.'});await TEST_CONTEXT.eventSource.emit('MESSAGE_RECEIVED',TEST_CONTEXT.chat.length-1);});
await page.waitForFunction(()=>document.querySelector('.kc-main .kc-scene')?.textContent.includes('Lobby'));await saved();
const branch=Object.values(JSON.parse(serverFile).data.characters['c.png'].branches)[0];assert.equal(branch.current.people.character.nude,false);assert.deepEqual(branch.current.people.character.items.map(i=>i.id).sort(),['bottom-0','shoe','top-0']);assert.equal(branch.outfitMemory.character.beforeUndress.length,3);
assert.ok(JSON.parse((await page.evaluate(()=>calls.at(-1))).messages[1].content).outfitMemory.character.beforeUndress.length===3);

// Mobile changes use the same server even without secure-context randomUUID (LAN HTTP).
await mobile.evaluate(()=>{Object.defineProperty(crypto,'randomUUID',{configurable:true,value:undefined});window.dispatchEvent(new Event('focus'));});
await mobile.waitForFunction(()=>document.querySelector('.kc-storage-status')?.textContent==='서버 저장됨');
await mobile.locator('[data-action="close"]').click();await mobile.locator('.kc-extension-settings [name="mascotLocked"]').uncheck();
await mobile.waitForFunction(()=>document.querySelector('.kc-storage-status')?.textContent==='서버 저장됨');
await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForFunction(()=>document.querySelector('.kc-extension-settings [name="mascotLocked"]')?.checked===false);
assert.equal(JSON.parse(serverFile).data.settings.mascotLocked,false);
await page.locator('[data-action="edit"]').click();await page.locator('[name="nude"]').check();await page.locator('[data-action="save-outfit"]').click();assert.match(await page.locator('.kc-main').innerText(),/완전 탈의/);
await page.locator('[data-action="settings"]').click();await page.locator('[data-action="delete-chat"]').click();assert.match(await page.locator('.kc-main').innerText(),/초기화/);
await page.locator('[data-action="settings"]').click();await page.locator('[data-action="delete-all"]').click();await saved();assert.equal(JSON.parse(serverFile).data,null);await mobile.evaluate(()=>window.dispatchEvent(new Event('focus')));await mobile.waitForFunction(()=>document.querySelector('#kc-enabled')?.checked===false);assert.ok(uploadCount>0);await mobileContext.close();assert.equal(await page.evaluate(()=>localStorage.getItem('kikki-closet:v1')),null);assert.equal(await page.locator('#kc-enabled').isChecked(),false);
await page.setViewportSize({width:1000,height:900});await page.evaluate(()=>{document.documentElement.style.setProperty('--SmartThemeBodyColor','#eee8f2');document.documentElement.style.setProperty('--SmartThemeBlurTintColor','#27232d');document.documentElement.style.setProperty('--SmartThemeQuoteColor','#a88bbb');document.documentElement.style.setProperty('--SmartThemeBorderColor','#776b82');});await page.locator('[data-action="tab-options"]').click();await page.screenshot({path:path.join(root,'test-results/desktop-dark.png'),fullPage:true});const desktopPaper=await page.locator('.kc-paper').boundingBox();assert.ok(Math.abs(desktopPaper.width/desktopPaper.height-2/3)<.002);await page.locator('[data-action="tab-actual"]').click();assert.deepEqual(await page.locator('.kc-paper').boundingBox(),desktopPaper);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('PASS: wardrobe quotas/completion failure preservation, closet selection/layout, undress-to-place transition recovery, target-specific sources, original notebook aspect ratio and stable size across tabs, drag/restore/lock/visual viewport, cross-browser server persistence, swipe/hide, deletion, outgoing injection; no browser errors');
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}
