import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.KIKKI_PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(fileURLToPath(new URL('..',import.meta.url)));
const fixture=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/scripts/extensions/third-party/CHAT_CLOSET/style.css"><style>:root{--SmartThemeBodyColor:#383240;--SmartThemeBlurTintColor:#f6f0e8;--SmartThemeQuoteColor:#886895;--SmartThemeBorderColor:#cfc2d8}body{margin:0;background:#eee7f0;font-family:Arial}#chat{position:fixed;inset:0;z-index:500;background:#ddd2e5;pointer-events:none}</style></head><body><div id="chat">실리 채팅 레이어</div><div id="extensions_settings"></div><div id="extensionsMenu"></div><script>
window.calls=[];window.listeners={};window.modelWait=null;const events=['GENERATE_AFTER_DATA','MESSAGE_RECEIVED','MESSAGE_SWIPED','MESSAGE_EDITED','MESSAGE_UPDATED','MESSAGE_DELETED','MESSAGE_SWIPE_DELETED','GENERATION_ENDED','CHAT_CHANGED','GENERATION_STOPPED','CHAT_DELETED','CHAT_RENAMED'];window.TEST_CONTEXT={characters:[{avatar:'c.png',name:'서윤',description:'학생. 단정한 캐주얼을 좋아함.',chat:'chat-a'}],characterId:0,chatId:'chat-a',name1:'나',name2:'서윤',chat:[{send_date:'0',is_user:false,name:'서윤',mes:'집에서 쉬고 있다.'}],extensionSettings:{regex:[],disabledExtensions:[]},powerUserSettings:{persona_description:'실용적인 캐주얼 선호'},eventTypes:Object.fromEntries(events.map(x=>[x,x])),eventSource:{on(k,fn){(listeners[k]??=[]).push(fn)},async emit(k,...args){for(const fn of listeners[k]||[])await fn(...args)}}};
const shoe={id:'shoe',category:'신발',name:'운동화',color:'흰색',features:['캔버스'],brand:'CONVERSE',source:'추정 보유',available:true};window.SERVICE={getSupportedProfiles:()=>[{id:'profile',name:'테스트 연결',model:'fixture'}],getProfile:()=>({id:'profile'}),validateProfile:()=>{},async sendRequest(id,messages,tokens,options){window.calls.push({id,messages,tokens});if(window.modelWait)return await new Promise(resolve=>window.releaseModel=()=>resolve({content:JSON.stringify(window.nextScene)}));const system=messages[0].content,data=JSON.parse(messages[1].content);if(system.includes('인물 분석기'))return {content:JSON.stringify({character:{fields:{'직업':{value:'학생',certainty:'명시',evidence:'시트'}},wardrobe:[shoe]},persona:{fields:{},wardrobe:[]}})};if(system.includes('ok'))return {content:'{"ok":true}'};const last=data.messages.at(-1)?.content||'';return {content:JSON.stringify({scene:{place:last.includes('집')?'집':'거리',activity:'이동'},people:{character:{nude:false,items:last.includes('맨발')?[]:['shoe']},persona:{nude:false,items:[]}},newItems:{character:[],persona:[]}})};}};
</script><script type="module" src="/scripts/extensions/third-party/CHAT_CLOSET/index.js"></script></body></html>`;
const server=createServer(async(req,res)=>{try{const u=req.url.split('?')[0];if(u==='/'){res.setHeader('Content-Type','text/html');res.end(fixture);return;}const modules={'/scripts/extensions.js':'export function getContext(){return window.TEST_CONTEXT}', '/scripts/extensions/shared.js':'export const ConnectionManagerRequestService=window.SERVICE;', '/scripts/world-info.js':'export const world_names=["복식 규칙"];export async function loadWorldInfo(){return {entries:{1:{comment:"날씨",content:"겨울에는 겉옷",disable:false}}}}'};if(modules[u]){res.setHeader('Content-Type','text/javascript');res.end(modules[u]);return;}const rel=u.replace('/scripts/extensions/third-party/CHAT_CLOSET/','');const file=path.resolve(root,rel);if(!file.startsWith(root+path.sep))throw Error('path');const bytes=await readFile(file);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.webp')?'image/webp':'text/plain');res.end(bytes);}catch{res.statusCode=404;res.end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
let browser;try{
browser=await chromium.launch({channel:process.env.KIKKI_BROWSER_CHANNEL||(process.platform==='win32'?'msedge':undefined),headless:true});const page=await browser.newPage({viewport:{width:360,height:780}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('.kc-extension-settings summary').click();await page.locator('#kc-enabled').check();await page.locator('.kc-extension-settings button').click();await page.locator('[data-action="settings"]').click();await page.locator('[name="profileId"]').selectOption('profile');await page.locator('[data-action="test"]').click();await page.locator('[data-action="sub-close"]').click();await page.locator('[data-action="tab-options"]').click();await page.locator('[data-action="analyze"]').click();await page.locator('[data-action="profile-persona"]').click();assert.equal(await page.locator('.kc-sub [name="직업"]').count(),1);await page.locator('[data-action="save-profile"]').click();await page.locator('[data-action="tab-actual"]').click();
const center=await page.locator('#kikki-closet-dialog').boundingBox();assert.ok(Math.abs(center.x+center.width/2-180)<2);assert.ok(Math.abs(center.y+center.height/2-390)<2);await page.screenshot({path:path.join(root,'test-results/mobile.png'),fullPage:true});
await page.evaluate(async()=>{TEST_CONTEXT.chat.push({send_date:'1',is_user:true,mes:'외출 준비를 한다.'});await kikkiClosetInterceptor(TEST_CONTEXT.chat,4096,()=>{throw Error('unexpected abort')},'normal');const p={prompt:[{role:'system',content:'<kikki_outfit>OLD</kikki_outfit>'}]};await TEST_CONTEXT.eventSource.emit('GENERATE_AFTER_DATA',p,false);window.injected=p.prompt[0].content;});assert.match(await page.evaluate(()=>window.injected),/운동화/);assert.doesNotMatch(await page.evaluate(()=>window.injected),/OLD|baseline|profiles/);await page.screenshot({path:path.join(root,'test-results/mobile-outfit.png'),fullPage:true});
await page.evaluate(async()=>{TEST_CONTEXT.chat.push({send_date:'2',is_user:false,swipe_id:0,mes:'신발을 신고 밖으로 나갔다.'});await TEST_CONTEXT.eventSource.emit('MESSAGE_RECEIVED',2)});await page.waitForTimeout(500);await page.evaluate(async()=>{TEST_CONTEXT.chat[2].swipe_id=1;TEST_CONTEXT.chat[2].mes='맨발로 밖으로 나갔다.';await TEST_CONTEXT.eventSource.emit('MESSAGE_SWIPED',2)});await page.waitForTimeout(500);assert.equal(await page.locator('.kc-person').first().locator('dd').filter({hasText:'운동화'}).count(),0);
await page.evaluate(async()=>{TEST_CONTEXT.chat[2].is_system=true;await TEST_CONTEXT.eventSource.emit('MESSAGE_UPDATED',2)});await page.waitForTimeout(500);assert.ok(await page.locator('.kc-person').first().locator('dd').filter({hasText:'운동화'}).count());
await page.locator('[data-action="edit"]').click();await page.locator('[name="nude"]').check();await page.locator('[data-action="save-outfit"]').click();assert.match(await page.locator('.kc-main').innerText(),/완전 탈의/);
await page.locator('[data-action="settings"]').click();await page.locator('[data-action="delete-chat"]').click();assert.match(await page.locator('.kc-main').innerText(),/초기화/);
await page.locator('[data-action="settings"]').click();await page.locator('[data-action="delete-all"]').click();assert.equal(await page.evaluate(()=>localStorage.getItem('kikki-closet:v1')),null);assert.equal(await page.locator('#kc-enabled').isChecked(),false);
await page.setViewportSize({width:1000,height:900});await page.screenshot({path:path.join(root,'test-results/desktop.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('PASS: real extension entry point, profile connection, analysis, mobile centered top-layer dialog, swipe/hide restore, manual edit, deletion, outgoing tag injection, no browser errors');
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}
